# Project information
site_name: 'Blog by Dirwalk'
site_description: 'A blog by DirWalk'
site_author: 'DirWalk'
site_url: 'https://dirwalk.com'

# Repository
repo_name: 'DirWalk/site'
repo_url: 'https://github.com/DirWalk/site'

# Copyright
# copyright: 'Copyright &copy; 2016 - 2017 Martin Donath'

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  #logo: 'images/logo.png'
  logo:
    icon: 'code'

# Customization
extra:
    social:
    - type: 'github'
      link: 'https://github.com/DirWalk'
    - type: 'reddit'
      link: 'https://www.reddit.com/user/DirWalk'
    - type: 'twitter'
      link: 'https://twitter.com/DirWalk'
    - type: 'envelope-o'
      link: 'mailto:dirwalk@pm.me'
    - type: 'book'
      link: 'https://wiki.dirwalk.com'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  # - toc:
  #     permalink: true

plugins:
  - search
  - awesome-pages
  - redirects:
      redirect_maps:
        'wiki.md': 'https://wiki.dirwalk.com'
